services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default:/etc/nginx/sites-available/default
    depends_on:
      - php
    networks:
      - lemp-stack

  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./website:/var/www/html
    networks:
      - lemp-stack

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: my_database
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lemp-stack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      - lemp-stack

volumes:
  db_data:

networks:
  lemp-stack:
    driver: bridge
